### ISSUE TITLE
JPL willing to release corresponding IMCE sysml profiles?

### ISSUE THREAD

**Issue by treachler** [JPL-IMCE/gov.nasa.jpl.imce.ontologies.public#6]
Hey all, I am just wondering if releasing the corresponding sysml profiles is in the plans / possible?
thanks!

**Comment by NicolasRouquette** [comment]
Yes it is; we're working on setting up a continuous integration service to generate them from sources and publish them to bintray as a MagicDraw installable zip add-on resource.

**Comment by treachler** [comment]
That is great to hear. I have been working on building a magic draw profile based on the released ontologies. The mapping has been overwhelming :)  Thanks!
